---
name: Lint Code Base

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  call-super-linter:
    # use Reusable Workflows to call my linter config remotely
    # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
    uses: bretfisher/super-linter-workflow/.github/workflows/super-linter.yaml@main
    with:
      devops-only: true
      filter-regex-exclude: .*compose-sample-3/html/.*
